Indent exit postambles on usage functions
I think Vim was refusing to indent these by default due to the EOF at
the start of the previous non-blank line. I'd rather try to clarify that
these are still part of the function, not the main script body.

diff --git a/lib/svb-create b/lib/svb-create
--- a/lib/svb-create
+++ b/lib/svb-create
@@ -15,11 +15,11 @@ CLI to upload them to S3. The archives will be uploaded under a directory named
 with the current UNIX timestamp (`date +%s`).
 EOF
 
-if [ "$#" -eq 1 ]; then
-  echo -e "\nerror: $1"
-fi
+  if [ "$#" -eq 1 ]; then
+    echo -e "\nerror: $1"
+  fi
 
-exit 1
+  exit 1
 }
 
 if [ "$#" -lt 1 ]; then
diff --git a/lib/svb-recent b/lib/svb-recent
--- a/lib/svb-recent
+++ b/lib/svb-recent
@@ -15,11 +15,11 @@ bucket. It assumes that all folders in the bucket were created by `svb backup`,
 and that their names take the form of UNIX timestamps.
 EOF
 
-if [ "$#" -eq 1 ]; then
-  echo -e "\nerror: $1"
-fi
+  if [ "$#" -eq 1 ]; then
+    echo -e "\nerror: $1"
+  fi
 
-exit 1
+  exit 1
 }
 
 if [ "$#" -lt 1 ]; then
diff --git a/lib/svb-restore b/lib/svb-restore
--- a/lib/svb-restore
+++ b/lib/svb-restore
@@ -18,11 +18,11 @@ If no volumes are specified, all volumes in the S3 directory will be restored.
 svb restore will not restore to a Docker volume that already exists.
 EOF
 
-if [ "$#" -eq 1 ]; then
-  echo -e "\nerror: $1"
-fi
+  if [ "$#" -eq 1 ]; then
+    echo -e "\nerror: $1"
+  fi
 
-exit 1
+  exit 1
 }
 
 if [ "$#" -lt 1 ]; then
diff --git a/lib/svb-show b/lib/svb-show
--- a/lib/svb-show
+++ b/lib/svb-show
@@ -15,11 +15,11 @@ contents. This may help you verify that backups are working as expected, and
 that the archives in the backup are not corrupted.
 EOF
 
-if [ "$#" -eq 1 ]; then
-  echo -e "\nerror: $1"
-fi
+  if [ "$#" -eq 1 ]; then
+    echo -e "\nerror: $1"
+  fi
 
-exit 1
+  exit 1
 }
 
 if [ "$#" -lt 1 ]; then
@@ -53,4 +53,3 @@ echo "$VOLS_IN_BACKUP" | while read -r VOLUME; do
 
   echo
 done
-
diff --git a/svb b/svb
--- a/svb
+++ b/svb
@@ -32,12 +32,12 @@ Notes:
     before performing backup or restore operations
 EOF
 
-if [ "$#" -eq 1 ]; then
-  echo -e "\nerror: $1"
-  exit 1
-fi
+  if [ "$#" -eq 1 ]; then
+    echo -e "\nerror: $1"
+    exit 1
+  fi
 
-exit 0
+  exit 0
 }
 
 if [ "$#" -lt 1 ] || [ "$1" = "help" ]; then
